# Generated by Django 3.2.3 on 2021-05-18 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=51)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=51)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=51)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glass.car')),
            ],
        ),
        migrations.CreateModel(
            name='Glass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=51)),
                ('description', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glass.car')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glass.model')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glass.company'),
        ),
    ]
