# Generated by Django 3.2.3 on 2021-05-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=51)),
                ('car', models.CharField(max_length=51)),
                ('description', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
    ]
