# Generated by Django 3.2.3 on 2021-05-25 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoparts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
